name: PEP8 Style Check
on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install tools
        run: python -m pip install --upgrade pip pycodestyle

      - name: Check Style
        run: pycodestyle . --exclude=.git,__pycache__,.venv,venv,build,dist
